# Notification System Configuration
# Defines channels and their decorators

channels:
  # Console channel for development/testing
  console:
    type: ConsoleChannel
    enabled: true
    config:
      format: pretty
      colored: true
    decorators:
      - type: logging
        log_level: INFO

  # Email channel via SMTP
  email:
    type: EmailChannel
    enabled: true
    config:
      smtp_host: ${SMTP_HOST:smtp.gmail.com}
      smtp_port: ${SMTP_PORT:587}
      username: ${SMTP_USERNAME:user@example.com}
      password: ${SMTP_PASSWORD:password}
      from_email: ${SMTP_FROM_EMAIL:noreply@example.com}
      use_tls: true
    decorators:
      - type: retry
        max_retries: 3
        initial_delay: 1.0
        max_delay: 60.0
        backoff_multiplier: 2.0
      - type: logging
        log_level: INFO
      - type: rate_limit
        rate_limit: 100
        time_window: 3600

  # Webhook channel for API integrations
  webhook:
    type: WebhookChannel
    enabled: true
    config:
      timeout: 30
      verify_ssl: true
      headers:
        User-Agent: NotificationSystem/1.0
    decorators:
      - type: retry
        max_retries: 2
        initial_delay: 0.5
        max_delay: 30.0
        backoff_multiplier: 2.0
      - type: logging
        log_level: DEBUG
      - type: rate_limit
        rate_limit: 50
        time_window: 60

# Default decorator settings (optional - for documentation)
defaults:
  decorators:
    retry:
      max_retries: 3
      initial_delay: 1.0
      max_delay: 60.0
      backoff_multiplier: 2.0
    logging:
      log_level: INFO
    rate_limit:
      rate_limit: 10
      time_window: 60
